version: '2'

services:
  client:
    build: .
    networks:
      - database
    environment:
      - HOST=mariadb
      - USER=root
      - PASS=1234
    depends_on:
      - mariadb

  mariadb:
    image: mariadb
    networks:
      - database
    environment:
      - MYSQL_ROOT_PASSWORD=1234


networks:
  database:
