version: '2'

services:
  app:
    build: .
    volumes:
      - ./app:/usr/src/app
    ports:
      - "3000:3000"
    networks:
      - database
    depends_on:
      - redis

  redis:
    image: redis:alpine
    networks:
      database:
        aliases:
          - my-redis


networks:
  database: